---
abstract: 'SRU server backed by a searchable Catmandu::Store'
author:
  - 'Nicolas Steenlant, C<< <nicolas.steenlant at ugent.be> >>'
build_requires:
  Dancer::Test: '1.3123'
  Test::More: '0.88'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer-Plugin-Catmandu-SRU
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Catmandu: '0.8014'
  Catmandu::Exporter::Template: '0.03'
  Dancer: '1.3123'
  SRU: '1.01'
  perl: v5.10.1
resources:
  bugtracker: https://github.com/LibreCat/Dancer-Plugin-Catmandu-SRU/issues
  homepage: https://github.com/LibreCat/Dancer-Plugin-Catmandu-SRU
  repository: https://github.com/LibreCat/Dancer-Plugin-Catmandu-SRU.git
version: '0.03'
x_contributors:
  - 'Nicolas Steenlant <nicolas.steenlant@gmail.com>'
  - 'vpeil <vitali.peil@uni-bielefeld.de>'
